### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by Roglue** [Roglue/ruvur#2]
- [ ] Turn on GitHub Pages
- [ ] Outline my portfolio
- [ ] Introduce myself to the world

**Comment by Roglue** [comment]
- [x] Turn on GitHub Pages
- [x] Outline my portfolio
- [x] Introduce myself to the world
